### ISSUE TITLE
hess_part is bugged

### ISSUE THREAD

**Issue by zgbkdlm** [zgbkdlm/tme#7]
@AdrienCorenflos  I just notice that the double linearize implementation of the matrix-Hessian-matrix multiplication is wrong. The `hess_prod_2` additionally computes the derivative of dispersion which should not be there. 

```python
  def hess_prod_1(z, f):
      # This computes the Jacobian-vector product J[f](z) * b(z)
      _, linearized_f = linearize(f, z)
      return vmap(linearized_f, in_axes=1, out_axes=0)(_format_dispersion(dispersion(z)))

  def hess_prod_2(z, f):
      # This computes the double Jacobian-vector product J[z -> J[f](z) * b(z)](z) * b(z).T
      # This is an equivalent, but more efficient way, to computing the Hessian form b(z).T * H[f](z) * b(z)
      # TODO: Verify is linearize is faster than vectorized vjp here.
      _, linearized_f = linearize(lambda zz: hess_prod_1(zz, f), z)
      return vmap(linearized_f, in_axes=0, out_axes=1)(_format_dispersion(dispersion(z)).T)
```

The unit tests passed because the test models have constant dispersions.

**Comment by AdrienCorenflos** [comment]
Oh! Right! Maybe we should take the chance to try and implement this with JET then?

**Comment by AdrienCorenflos** [comment]
In the meantime there should be a way to fix this with stop_gradient?

**Comment by AdrienCorenflos** [comment]
There is also some doc in Jax about using Hessian vector products

**Comment by zgbkdlm** [comment]
I have fixed the bug, and I will push it to a branch. 

Let's try the JET stuff indeed, I will create a branch for that.

**Comment by AdrienCorenflos** [comment]
Send a pr so I can confirm there's no better way :)

**Comment by AdrienCorenflos** [comment]
> Let's try the JET stuff indeed, I will create a branch for that. 

Doc has improved a lot so it's worth trying again. I thin @pnkraemer is to thanks for that
